Morphyn Language: Morphyn.Parser.Entity Class Reference
Morphyn.Parser.Entity Class Reference
Represents an entity in language.
Public Member Functions
void BuildCache ()
Entity Clone ()
Properties
required string Name [get, set]
Dictionary< string, object?> Fields = new Dictionary<string, object>() [get, set]
List< Event > Events = new List<Event>() [get, set]
bool IsDestroyed = false [get, set]
Dictionary< string, Event > EventCache = new() [get, set]
Detailed Description
Represents an entity in language.
Definition at line 9 of file Entity.cs.
Member Function Documentation
BuildCache()
void Morphyn.Parser.Entity.BuildCache ()
Definition at line 17 of file Entity.cs.
References Morphyn.Parser.Entity.EventCache, and Morphyn.Parser.Entity.Events.
Clone()
Entity Morphyn.Parser.Entity.Clone ()
Definition at line 22 of file Entity.cs.
References Morphyn.Parser.Entity.EventCache, Morphyn.Parser.Entity.Events, Morphyn.Parser.Entity.Fields, Morphyn.Parser.Entity.IsDestroyed, and Morphyn.Parser.Entity.Name.
Property Documentation
EventCache
Dictionary<string, Event> Morphyn.Parser.Entity.EventCache = new() get set
Definition at line 15 of file Entity.cs.
Referenced by Morphyn.Parser.Entity.BuildCache(), and Morphyn.Parser.Entity.Clone().
Events
List<Event> Morphyn.Parser.Entity.Events = new List<Event>() get set
Definition at line 13 of file Entity.cs.
Referenced by Morphyn.Parser.Entity.BuildCache(), and Morphyn.Parser.Entity.Clone().
Fields
Dictionary<string, object?> Morphyn.Parser.Entity.Fields = new Dictionary<string, object>() get set
Definition at line 12 of file Entity.cs.
Referenced by Morphyn.Parser.Entity.Clone(), and Morphyn.Runtime.MorphynEvaluator.EvaluateExpression().
IsDestroyed
bool Morphyn.Parser.Entity.IsDestroyed = false get set
Definition at line 14 of file Entity.cs.
Referenced by Morphyn.Parser.Entity.Clone().
Name
required string Morphyn.Parser.Entity.Name get set
Definition at line 11 of file Entity.cs.
Referenced by Morphyn.Parser.Entity.Clone().
The documentation for this class was generated from the following file:
Morphyn.Parser/Models/Entity.cs