#if UNITY_EDITOR
using System.IO;
using System.Linq;
using UnityEditor;
using UnityEditor.Build;
using UnityEditor.Build.Reporting;
using UnityEngine;

namespace Morphyn.Editor
{
    /// <summary>
    /// Automatically copies all Morphyn stdlib .morph files into Resources/MorphynStdLib/
    /// before a build, and removes them after the build completes.
    /// This means users never have to manually manage stdlib placement.
    /// </summary>
    public class MorphynBuildProcessor : IPreprocessBuildWithReport, IPostprocessBuildWithReport
    {
        private const string ResourcesTargetFolder = "Assets/Resources/MorphynStdLib";
        private const string StdlibMarkerFilename   = "MorphynStdLib_AutoGenerated.marker";

        public int callbackOrder => 0;

        public void OnPreprocessBuild(BuildReport report)
        {
            CopyStdlibToResources();
        }

        public void OnPostprocessBuild(BuildReport report)
        {
            CleanupStdlibFromResources();
        }

        private static void CopyStdlibToResources()
        {
            // Find all .morph TextAssets that live inside a folder named "StdLibs" or "stdlib"
            string[] guids = AssetDatabase.FindAssets("t:TextAsset");
            bool any = false;

            foreach (var guid in guids)
            {
                string assetPath = AssetDatabase.GUIDToAssetPath(guid);

                if (!assetPath.EndsWith(".morph", System.StringComparison.OrdinalIgnoreCase))
                    continue;

                // Only copy files that are inside a StdLib/stdlib/StdLibs folder
                string[] parts = assetPath.Replace("\\", "/").Split('/');
                bool isStdlib = parts.Any(p =>
                    p.Equals("StdLibs",  System.StringComparison.OrdinalIgnoreCase) ||
                    p.Equals("StdLib",   System.StringComparison.OrdinalIgnoreCase) ||
                    p.Equals("stdlib",   System.StringComparison.OrdinalIgnoreCase) ||
                    p.Equals("MorphynStdLib", System.StringComparison.OrdinalIgnoreCase));

                if (!isStdlib) continue;

                if (!Directory.Exists(ResourcesTargetFolder))
                    Directory.CreateDirectory(ResourcesTargetFolder);

                string fileName    = Path.GetFileName(assetPath);
                string destination = Path.Combine(ResourcesTargetFolder, fileName);

                File.Copy(assetPath, destination, overwrite: true);
                Debug.Log($"[Morphyn] Copied stdlib '{fileName}' to Resources for build.");
                any = true;
            }

            if (any)
            {
                // Write marker so cleanup knows we created this folder
                File.WriteAllText(
                    Path.Combine(ResourcesTargetFolder, StdlibMarkerFilename),
                    "auto-generated by MorphynBuildProcessor");

                AssetDatabase.Refresh();
            }
        }

        private static void CleanupStdlibFromResources()
        {
            string markerPath = Path.Combine(ResourcesTargetFolder, StdlibMarkerFilename);

            if (!File.Exists(markerPath)) return;

            // Remove only files we copied (marker present = we created the folder)
            if (Directory.Exists(ResourcesTargetFolder))
            {
                FileUtil.DeleteFileOrDirectory(ResourcesTargetFolder);
                FileUtil.DeleteFileOrDirectory(ResourcesTargetFolder + ".meta");
            }

            AssetDatabase.Refresh();
            Debug.Log("[Morphyn] Cleaned up stdlib from Resources after build.");
        }

        /// <summary>
        /// Can also be called manually from the menu if needed.
        /// </summary>
        [MenuItem("Morphyn/Copy Stdlib to Resources (manual)")]
        public static void CopyManual() => CopyStdlibToResources();

        [MenuItem("Morphyn/Remove Stdlib from Resources (manual)")]
        public static void CleanupManual() => CleanupStdlibFromResources();
    }
}
#endif